# set JEKYLL_ENV=development
# set JEKYLL_ENV=production
# bundle exec jekyll serve --future --unpublished

# Site settings
locale: "de"
repository: "gamue/gamue.github.io"
baseurl: ""


pagination:
  enabled: true
  debug: false
  per_page: 8
  permalink: /page:num/
  title: ':title - Seite :num'
  sort_reverse: true
  trail:
    before: 2
    after: 2



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_meta_data: true
      header:
        show_overlay_excerpt: false

  # _pages
  - scope:
      path: _pages/photography/*
      type: pages
    values:
      full_width: true
      typography: false
      lightbox: true
  - scope:
      path: _pages/countries/*
      type: pages
    values:
      layout: country
      search: true

autopages:
  enabled: true
  tags:
    layouts:
      - 'paginate_overview.html'
    title: 'Artikel aus der Kategorie :tag'
    permalink: '/tag/:tag'
    enabled: true
  categories:
    layouts:
      - 'paginate_overview.html'
    title: 'Artikel aus der Kategorie :cat'
    permalink: '/category/:cat'
    enabled: true
  collections:
    enabled: false

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
  profile: false

cloudinary:
  cloud_name: gamue
  only_prod: false
  verbose: true
  presets:

    thumbnail:
      min_width: 100
      max_width: 400
      min_heigth: 100
      max_heigth: 400
      fallback_max_width: 300
      steps: 3
      figure: never
