# set JEKYLL_ENV=development
# set JEKYLL_ENV=production
# bundle exec jekyll serve --future --unpublished

# Site settings
locale: "de"
title: "gamue.de: Blog von Johannes Ganzenmüller"
name: "Johannes Ganzenmüller"
email: johannes@gamue.de
description: "Auf diesem Blog dreht sich alles rund um die Themen Reisen, Fotografie und Technik."
repository: "gamue/gamue.github.io"
baseurl: ""
url: "https://gamue.de"
logo: "assets/images/j_logo_75.jpg"
og_image: "assets/images/j_logo.jpg"
words_per_minute: 200
search: true

# Site Author
author:
  name: "Johannes Ganzenmüller"
  location: "Berlin, Germany"

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - README.md
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown

pagination:
  enabled: true
  debug: false
  per_page: 8
  permalink: /page:num/
  title: ':title - Seite :num'
  sort_reverse: true
  trail:
    before: 2
    after: 2

timezone: 'Europe/Berlin'

comments:
  disqus:
    shortname: 'gamue'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      read_time: true
      show_date: true
      header:
        show_overlay_excerpt: false

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: _pages/photography
      type: pages
    values:
      classes: galleryPage
  - scope:
      path: _pages/countries
      type: pages
    values:
      classes: galleryPage
      comments: true
      search: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
  profile: false

cloudinary:
  cloud_name: gamue
  only_prod: false
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1000
      fallback_max_width: 800
      steps: 5
    thumbnail:
      min_width: 100
      max_width: 400
      min_heigth: 100
      max_heigth: 400
      fallback_max_width: 300
      steps: 3
      figure: never

analytics:
  google:
    tracking_id: "UA-177618947-1"

css_dir: "assets/css"

sass:
  style: compressed