# 'bundle exec jekyll serve'

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

# Site settings
locale: "de"
title: "gamue.de"
title_separator: "-"
subtitle: ""
name: "Johannes Ganzenmüller"
email: johannes@gamue.de
description: "Über Reisen, Photographie, Technik, Leben und sonstigen Spaß"
baseurl: ""
url: "https://gamue.de"
logo: "assets/images/j_logo_75.jpg"
masthead_title: " "
words_per_minute: 200
search: true

# Site Author
author:
  name: "Johannes Ganzenmüller"
  bio: ""
  location: "Berlin, Germany"

# Site Footer
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/gamue16/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gamue"

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown

paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 'Europe/Berlin'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

comments:
  provider: 'disqus'
  disqus:
    shortname: 'gamue'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      author_profile: false
      read_time: true
      header:
        show_overlay_excerpt: false

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        og_image: assets/images/j_logo.jpg
  - scope:
      path: _pages/photography
      type: pages
    values:
      classes: galleryPage
  - scope:
      path: _pages/countries
      type: pages
    values:
      classes: galleryPage
      comments: true
      search: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
  profile: false