name: Build code

on:
  pull_request:
    branches:
      - main

jobs:
  pr-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install dependencies and build
        run: |
          npm ci
          npm run lint
          npm run prettier
          npm run build
