name: Build code

on:
  pull_request:
    branches:
      - main

jobs:
  pr-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies and build
        run: |
          npm ci
          npm run lint
          npm run prettier
          npm run build
